### ISSUE TITLE
Wrong properties set when using ESDTIssueBuilder

### ISSUE THREAD

**Issue by EtienneWallet** [multiversx/mx-sdk-py-core#39]
# Description

When setting all issue arguments to `False` using `ESDTIssueBuilder`, the issued token ends up with the following properties as `True`: `can_upgrade` and `can_add_special_roles`.

```python
tx = ESDTIssueBuilder(
    config=token_management_builders.get_builder_config(),
    issuer=sender_account.address,
    token_name="TokenTest",
    token_ticker="TKT",
    initial_supply=100,
    num_decimals=1,
    can_add_special_roles=False,
    can_burn=False,
    can_change_owner=False,
    can_freeze=False,
    can_mint=False,
    can_pause=False,
    can_upgrade=False,
    can_wipe=False
    ).build()
```
[devnet transaction](https://devnet-explorer.multiversx.com/transactions/360d6966d31477853d8a30d896ba05e1034b363cf1bbfff3b0929fcd81744931#smart)

[issued token on the devnet](https://devnet-explorer.multiversx.com/tokens/TKT-75d805)

![image](https://github.com/multiversx/mx-sdk-py-core/assets/116115319/a43799dd-992a-4d01-97ea-23742a7df2f5)

# Cause

I suspect that `mx-sdk-py-core` assumes that the default values of each properties is `False` so as a result, in the above example, it doesn't specify any properties inside the transaction. However, some of the properties' default is `True` on the blockchain.

The faulty code part is in the method [_build_payload_parts](https://github.com/multiversx/mx-sdk-py-core/blob/main/multiversx_sdk_core/transaction_builders/esdt_builders.py) below: `*(args_to_strings(["canUpgrade", "true"]) if self.can_upgrade else [])` and `*(args_to_strings(["canAddSpecialRoles", "true"]) if self.can_add_special_roles else [])` are not correct.

```python
    def _build_payload_parts(self) -> List[str]:
        return [
            "issue",
            arg_to_string(self.token_name),
            arg_to_string(self.token_ticker),
            arg_to_string(self.initial_supply),
            arg_to_string(self.num_decimals),
            *(args_to_strings(["canFreeze", "true"]) if self.can_freeze else []),
            *(args_to_strings(["canWipe", "true"]) if self.can_wipe else []),
            *(args_to_strings(["canPause", "true"]) if self.can_pause else []),
            *(args_to_strings(["canMint", "true"]) if self.can_mint else []),
            *(args_to_strings(["canBurn", "true"]) if self.can_burn else []),
            *(args_to_strings(["canChangeOwner", "true"]) if self.can_change_owner else []),
            *(args_to_strings(["canUpgrade", "true"]) if self.can_upgrade else []),
            *(args_to_strings(["canAddSpecialRoles", "true"]) if self.can_add_special_roles else [])
        ]
```
# Possible Solutions

## Solution 1

Replace:
- `*(args_to_strings(["canUpgrade", "true"]) if self.can_upgrade else [])`  by `*(args_to_strings(["canUpgrade", "false"]) if not self.can_upgrade else [])` 
- `*(args_to_strings(["canAddSpecialRoles", "true"]) if self.can_add_special_roles else [])` by `*(args_to_strings(["canAddSpecialRoles", "false"]) if not self.can_add_special_roles else [])`

This solution is easy but we will have to maintain the consistency between these default values and the ones on the blockchain.

## Solution 2

We always specify the values of all properties, regardless of the default values:

```python
    def _build_payload_parts(self) -> List[str]:
        return [
            "issue",
            arg_to_string(self.token_name),
            arg_to_string(self.token_ticker),
            arg_to_string(self.initial_supply),
            arg_to_string(self.num_decimals),
            *(args_to_strings(["canFreeze", str(self.can_freeze).lower()])),
            ...
            *(args_to_strings(["canAddSpecialRoles", str(self.can_add_special_roles).lower()]))
        ]
```

This will make the transaction consume more gas but you will be sure that the end result will always be what the user specified, regardless of the default values on the blockchain.

# Next Steps

I'll be happy to write the PR if you need, just let me know if there is a solution you prefer (from the two above or anything else).

Thank you :smile:

**Comment by EtienneWallet** [comment]
Thank you for your answer and for taking care of this @popenta !
I have nothing more to add on this issue then.

I didn't notice that this library was shifting towards transaction factories instead of builders, so I'll look into it once `v1.0.0` is out.
Have a nice day :grin:

**Comment by popenta** [comment]
Indeed, we are shifting towards transaction factories. The sdk specifications are still in progress, but if you'd like you can take a look [here](https://github.com/multiversx/mx-sdk-specs). Since the fix will only come in a future release I'll leave this issue open until then.

Thank you again for reporting this problem and have a nice day!

**Comment by popenta** [comment]
This is fixed. Every property is now explicitly set to either `true` or `false`.

**Comment by EtienneWallet** [comment]
Wonderful, thank you for your work 💪
