### ISSUE TITLE
Gas Estimation Not Implemented in Contract Call Builder

### ISSUE THREAD

**Issue by SkullElf** [multiversx/mx-sdk-py-core#57]
Please implement the estimation function in the contract call builder.
Can't use this object in a relayed transaction v2 builder because it tries to build the Transaction object and can't handle gas limit being 0...

**Comment by andreibancioiu** [comment]
The matter should now be resolved in the new transaction factory for relayed transactions:
 - https://github.com/multiversx/mx-sdk-py/blob/main/multiversx_sdk/core/transactions_factories/relayed_transactions_factory.py
 - https://docs.multiversx.com/sdk-and-tools/sdk-py/sdk-py-cookbook/
