### ISSUE TITLE
Missing role `ESDTTransferRole` in the factory method for setting special role on fungible token

### ISSUE THREAD

**Issue by EtienneWallet** [multiversx/mx-sdk-py-core#71]
# Description

The method `create_transaction_for_setting_special_role_on_fungible_token` of the factory `TokenManagementTransactionsFactory` allows to set the roles `ESDTRoleLocalMint` and `ESDTRoleLocalBurn` but not the role `ESDTTransferRole`.

# Action

I write a PR to add an argument to allow to set this role.

**Comment by popenta** [comment]
Hello,

Thanks for reporting this. I've added the `ESDTTransferRole` on the `create_transaction_for_setting_special_role_on_fungible_token` method. The PR was done in the upcoming **sdk-py** package that will soon be released.

The PR can be found [here](https://github.com/multiversx/mx-sdk-py-incubator/pull/26).
